const ANIMALS = [
  ['tortue','🐢','Tortue','sage et paisible',['Patiente','Sereine','Fiable']], ['chat','🐱','Chat','douce et indépendante',['Curieuse','Élégante','Câline']],
  ['chien','🐶','Chien','loyale et pleine de joie',['Sociable','Fidèle','Enthousiaste']], ['hamster','🐹','Hamster','vive et adorable',['Ingénieuse','Joueuse','Organisée']],
  ['renard','🦊','Renard','maligne et créative',['Astucieuse','Créative','Aventurière']], ['lapin','🐰','Lapin','sensible et pétillante',['Douce','Rapide','Attentionnée']],
  ['dauphin','🐬','Dauphin','lumineuse et enthousiaste',['Joyueuse','Intuitive','Énergique']], ['panda','🐼','Panda','tendre et réconfortante',['Gentille','Zen','Attachante']],
  ['koala','🐨','Koala','tranquille et rêveuse',['Calme','Rêveuse','Affectueuse']], ['tigre-blanc','🐯','Tigre blanc','courageuse et magnétique',['Audacieuse','Fière','Déterminée']],
  ['ours','🐻','Ours','forte avec un grand cœur',['Protectrice','Généreuse','Robuste']], ['capybara','🦫','Capybara','chill et naturellement sociable',['Détendue','Sociable','Apaisante']]
].map(([id,emoji,name,description,traits]) => ({id,emoji,name,description,traits}));
const optionSets = [
 ['Prendre mon temps et observer','Me lover dans mon coin préféré','Retrouver toute ma bande','Préparer un petit trésor à grignoter','Imaginer un plan original','Sautiller vers une jolie surprise','Nager et rire dans l’eau','Partager un moment tout doux','Rêvasser au calme','Relever un défi qui me fait vibrer','Organiser un cocon pour les miens','Discuter tranquillement avec tout le monde'],
 ['Une balade lente dans la nature','Un après-midi confortable à la maison','Un pique-nique avec mes proches','Une activité minutieuse et amusante','Explorer un endroit mystérieux','Un jardin fleuri et joyeux','Une journée près des vagues','Un film réconfortant sous un plaid','Écouter la pluie en me reposant','Une aventure qui sort de l’ordinaire','Un feu de cheminée chaleureux','Un café tranquille entre amis'],
 ['Observer les étoiles en silence','Faire une sieste au soleil','Jouer à plusieurs sans m’arrêter','Ranger mes petites affaires','Résoudre une énigme','Offrir une attention mignonne','Plonger dans une nouvelle activité','Faire une pause gourmande','Rester dans mon nuage','Me dépasser','Aider quelqu’un qui compte','Profiter simplement du moment'],
 ['Un endroit calme et verdoyant','Un coussin moelleux','Un parc animé','Une petite cabane remplie de choses','Un sentier secret','Une prairie lumineuse','La plage','Un salon doux et cosy','Une branche tranquille','Une montagne impressionnante','Une forêt protectrice','Une terrasse paisible avec des amis']
];
const prompts = ['Quelle activité t’attire le plus ?', 'Pour te sentir bien, tu choisis…', 'Quel est ton super-pouvoir au quotidien ?', 'Quel décor te ressemble le plus ?', 'Quand tu as du temps libre, tu préfères…', 'Quelle qualité te rend fière ?', 'Ton week-end idéal ressemble à…', 'Face à une nouveauté, tu…', 'Quel petit plaisir choisis-tu ?', 'Dans un groupe, tu es plutôt…', 'Quelle énergie veux-tu partager ?', 'Quel cadeau te ferait sourire ?', 'Ton rythme de vie idéal est…', 'Quelle mission te donnerait envie ?', 'Quel mot te parle le plus ?', 'Ton moment préféré de la journée ?', 'Pour te ressourcer, tu…', 'Quelle aventure te tente ?', 'Quel type de musique te ressemble ?', 'Ton bonheur, c’est surtout…'];
let state = {name:'', scores:Object.fromEntries(ANIMALS.map(a=>[a.id,0])), question:0, result:null};
const app = document.querySelector('#app');
const getPhotos = () => JSON.parse(localStorage.getItem('animal-totem-photos') || '{}'); const savePhotos = p => localStorage.setItem('animal-totem-photos',JSON.stringify(p));
const getDiscovered = () => JSON.parse(localStorage.getItem('animal-totem-discovered') || '[]');
const discover = animalId => { const discovered = new Set(getDiscovered()); discovered.add(animalId); localStorage.setItem('animal-totem-discovered', JSON.stringify([...discovered])); };
function shell(content) { app.innerHTML = `<section class="screen">${content}</section>`; }
function home() { shell(`<div class="brand">🐾 TON TOTEM TOUT DOUX</div><h1>QUEL ANIMAL<br>ES-TU ?</h1><div class="hero-paws">🌸 🐾 🌸</div><p class="lead">Découvre l'animal qui fait battre ton cœur.</p><div class="actions"><button class="button" id="start">💗 COMMENCER</button><button class="button alt" id="gallery">📸 MA GALERIE</button></div>`); document.querySelector('#start').onclick=identity; document.querySelector('#gallery').onclick=gallery; }
function identity() { shell(`<div class="card"><div class="brand">💌 AVANT DE COMMENCER</div><h2>Comment t'appelles-tu ?</h2><p class="lead">Choisis un prénom, un nom ou ton petit pseudo.</p><label class="field">Prénom <input id="first" autocomplete="given-name" placeholder="Ex. Louise"></label><label class="field">Nom <input id="last" autocomplete="family-name" placeholder="Facultatif"></label><label class="field">Pseudo <input id="nick" placeholder="Ou ton pseudo préféré"></label><div class="actions"><button class="button" id="go">C'EST PARTI ! ✨</button><button class="button alt" id="back">← Retour</button></div></div>`); const fields=['first','last','nick'].map(id=>document.querySelector(`#${id}`)); const begin=()=>{const [f,l,n]=fields.map(field=>field.value.trim()); state.name=n||[f,l].filter(Boolean).join(' ')||'Toi'; quiz();}; fields.forEach((field,index)=>field.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault(); index<fields.length-1 ? fields[index+1].focus() : begin();}})); document.querySelector('#back').onclick=home; document.querySelector('#go').onclick=begin; fields[0].focus(); }
function quiz() { const q=state.question, opts=optionSets[q%optionSets.length]; shell(`<div class="progress-line"><span>QUESTION ${q+1} / ${prompts.length}</span><span>🐾</span></div><div class="progress"><i style="width:${q/prompts.length*100}%"></i></div><div class="card quiz-card"><h2 class="question">${prompts[q]}</h2><div class="answers">${opts.map((text,i)=>`<button class="answer" data-animal="${ANIMALS[i].id}">${text}</button>`).join('')}</div></div>`); document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{state.scores[b.dataset.animal]+=2; state.question++; state.question===prompts.length ? finish() : quiz();}); }
function finish(){ const ranked=[...ANIMALS].sort((a,b)=>state.scores[b.id]-state.scores[a.id]); if(state.scores[ranked[0].id]===state.scores[ranked[1].id]) bonus(ranked[0],ranked[1]); else result(ranked[0]); }
function bonus(a,b) { shell(`<div class="card"><div class="brand">💕 DERNIÈRE PETITE QUESTION</div><h2>Deux énergies te ressemblent beaucoup !</h2><p class="lead">Au choix, tu préfères suivre ton intuition ou créer une belle surprise ?</p><div class="actions"><button class="button" id="one">Suivre mon intuition ✨</button><button class="button alt" id="two">Créer une surprise 🎀</button></div></div>`); document.querySelector('#one').onclick=()=>result(a); document.querySelector('#two').onclick=()=>result(b); }
function result(animal) { state.result=animal; discover(animal.id); shell(`<div class="confetti">${['💗','🌸','✨','🐾','💖','🌷'].map((x,i)=>`<span style="left:${8+i*17}%;animation-delay:-${i*.4}s">${x}</span>`).join('')}</div><div class="card"><div class="brand">🎉 TON RÉSULTAT EST LÀ</div><p class="lead">${state.name}, tu es le</p><h2 class="result-name">${animal.name} !</h2><div class="animal">${animal.emoji}</div><p class="lead">Une personnalité <strong>${animal.description}</strong>. C'est une merveilleuse énergie à avoir près de soi !</p><div class="traits">${animal.traits.map(t=>`<span class="trait">${t}</span>`).join('')}</div><div class="actions"><button class="button" id="camera">📸 PRENDRE UNE PHOTO</button><button class="button alt" id="see-gallery">📸 MA GALERIE</button><button class="button alt small" id="again">🔄 REFAIRE LE QUIZ</button></div></div>`); document.querySelector('#camera').onclick=()=>{const photos=getPhotos(); (photos[animal.id]??=[]).push(createResultPhoto(animal)); savePhotos(photos); gallery();}; document.querySelector('#see-gallery').onclick=gallery; document.querySelector('#again').onclick=()=>{state={name:'',scores:Object.fromEntries(ANIMALS.map(a=>[a.id,0])),question:0,result:null};identity();}; }
function createResultPhoto(animal) { const canvas=document.createElement('canvas'), ctx=canvas.getContext('2d'), width=900, height=1200; canvas.width=width; canvas.height=height; const gradient=ctx.createLinearGradient(0,0,width,height); gradient.addColorStop(0,'#ffe8f1'); gradient.addColorStop(.48,'#fff8fb'); gradient.addColorStop(1,'#ffe1ed'); ctx.fillStyle=gradient; ctx.fillRect(0,0,width,height); ctx.fillStyle='rgba(255,255,255,.94)'; ctx.beginPath(); ctx.roundRect(65,100,770,1000,38); ctx.fill(); ctx.textAlign='center'; ctx.fillStyle='#5c3650'; ctx.font='900 25px system-ui'; ctx.fillText('🎉  TON RÉSULTAT EST LÀ',450,180); ctx.font='32px system-ui'; ctx.fillStyle='#84556e'; ctx.fillText(`${state.name}, tu es le`,450,270); ctx.font='900 70px system-ui'; ctx.fillStyle='#e94d8b'; ctx.fillText(`${animal.name.toUpperCase()} !`,450,360); ctx.font='190px system-ui'; ctx.fillText(animal.emoji,450,580); ctx.font='31px system-ui'; ctx.fillStyle='#84556e'; ctx.fillText(`Une personnalité ${animal.description}.`,450,710); ctx.fillText("C'est une merveilleuse énergie à avoir près de soi !",450,758); ctx.font='bold 26px system-ui'; ctx.fillStyle='#e94d8b'; ctx.fillText(animal.traits.join('   •   '),450,850); ctx.font='bold 24px system-ui'; ctx.fillStyle='#95677d'; ctx.fillText('Quel animal es-tu ?',450,1020); return canvas.toDataURL('image/png'); }
function gallery(){ const photos=getPhotos(), discovered=new Set(getDiscovered()), found=ANIMALS.filter(a=>discovered.has(a.id)); shell(`<div class="card"><button class="back" id="back">← Accueil</button><div class="gallery-header"><div><h2>Mon Pokédex 📸</h2><p class="muted">Les animaux que tu as découverts.</p></div><span class="counter">🐾 ${found.length} / ${ANIMALS.length}</span></div>${found.length?`<div class="collection">${found.map(a=>{const count=photos[a.id]?.length||0;return `<button class="animal-tile" data-id="${a.id}"><span class="tile-emoji">${a.emoji}</span><span><b>${a.name}</b><small>${count ? `${count} photo${count>1?'s':''} souvenir${count>1?'s':''}` : 'Animal découvert — aucune photo'}</small></span></button>`}).join('')}</div>`:`<p class="lead">Ton Pokédex est encore secret… Fais le quiz pour découvrir ton premier animal ! 💕</p>`}</div>`); document.querySelector('#back').onclick=home; document.querySelectorAll('.animal-tile').forEach(b=>b.onclick=()=>animalGallery(ANIMALS.find(a=>a.id===b.dataset.id))); }
function animalGallery(animal){const photos=getPhotos()[animal.id]||[];shell(`<div class="card"><button class="back" id="back">← Ma galerie</button><div class="animal">${animal.emoji}</div><h2>Mes photos de ${animal.name}</h2><p class="muted">${photos.length ? `${photos.length} joli${photos.length>1?'s':''} souvenir${photos.length>1?'s':''} à garder précieusement.` : "Tu as découvert cet animal ! Prends une photo de ton résultat lors de ta prochaine rencontre."}</p><div class="photos">${photos.map((src,i)=>`<img class="photo" src="${src}" alt="Souvenir ${i+1} - ${animal.name}">`).join('')}</div></div>`);document.querySelector('#back').onclick=gallery;}
home();
