const ANIMALS = [
  ['tortue','🐢','Tortue','sage et paisible',['Patiente','Sereine','Fiable']], ['chat','🐱','Chat','douce et indépendante',['Curieuse','Élégante','Câline']],
  ['chien','🐶','Chien','loyale et pleine de joie',['Sociable','Fidèle','Enthousiaste']], ['hamster','🐹','Hamster','vive et adorable',['Ingénieuse','Joueuse','Organisée']],
  ['renard','🦊','Renard','maligne et créative',['Astucieuse','Créative','Aventurière']], ['lapin','🐰','Lapin','sensible et pétillante',['Douce','Rapide','Attentionnée']],
  ['dauphin','🐬','Dauphin','lumineuse et enthousiaste',['Joyueuse','Intuitive','Énergique']], ['panda','🐼','Panda','tendre et réconfortante',['Gentille','Zen','Attachante']],
  ['koala','🐨','Koala','tranquille et rêveuse',['Calme','Rêveuse','Affectueuse']], ['tigre-blanc','🐯','Tigre blanc','courageuse et magnétique',['Audacieuse','Fière','Déterminée']],
  ['ours','🐻','Ours','forte avec un grand cœur',['Protectrice','Généreuse','Robuste']], ['capybara','🦫','Capybara','chill et naturellement sociable',['Détendue','Sociable','Apaisante']]
].map(([id,emoji,name,description,traits]) => ({id,emoji,name,description,traits}));
const optionSets = [
 ['Prendre mon temps et observer','Me lover dans mon coin préféré','Retrouver toute ma bande','Préparer un petit trésor à grignoter','Imaginer un plan original','Sautiller vers une jolie surprise','Nager et rire dans l’eau','Partager un moment tout doux','Rêvasser au calme','Relever un défi qui me fait vibrer','Organiser un cocon pour les miens','Discuter tranquillement avec tout le monde'],
 ['Une balade lente dans la nature','Un après-midi confortable à la maison','Un pique-nique avec mes proches','Une activité minutieuse et amusante','Explorer un endroit mystérieux','Un jardin fleuri et joyeux','Une journée près des vagues','Un film réconfortant sous un plaid','Écouter la pluie en me reposant','Une aventure qui sort de l’ordinaire','Un feu de cheminée chaleureux','Un café tranquille entre amis'],
 ['Observer les étoiles en silence','Faire une sieste au soleil','Jouer à plusieurs sans m’arrêter','Ranger mes petites affaires','Résoudre une énigme','Offrir une attention mignonne','Plonger dans une nouvelle activité','Faire une pause gourmande','Rester dans mon nuage','Me dépasser','Aider quelqu’un qui compte','Profiter simplement du moment'],
 ['Un endroit calme et verdoyant','Un coussin moelleux','Un parc animé','Une petite cabane remplie de choses','Un sentier secret','Une prairie lumineuse','La plage','Un salon doux et cosy','Une branche tranquille','Une montagne impressionnante','Une forêt protectrice','Une terrasse paisible avec des amis']
];
const prompts = ['Quelle activité t’attire le plus ?', 'Pour te sentir bien, tu choisis…', 'Quel est ton super-pouvoir au quotidien ?', 'Quel décor te ressemble le plus ?', 'Quand tu as du temps libre, tu préfères…', 'Quelle qualité te rend fière ?', 'Ton week-end idéal ressemble à…', 'Face à une nouveauté, tu…', 'Quel petit plaisir choisis-tu ?', 'Dans un groupe, tu es plutôt…', 'Quelle énergie veux-tu partager ?', 'Quel cadeau te ferait sourire ?', 'Ton rythme de vie idéal est…', 'Quelle mission te donnerait envie ?', 'Quel mot te parle le plus ?', 'Ton moment préféré de la journée ?', 'Pour te ressourcer, tu…', 'Quelle aventure te tente ?', 'Quel type de musique te ressemble ?', 'Ton bonheur, c’est surtout…'];
let state = {name:'', scores:Object.fromEntries(ANIMALS.map(a=>[a.id,0])), question:0, result:null};
const app = document.querySelector('#app'); const camera = document.querySelector('#camera-input');
const getPhotos = () => JSON.parse(localStorage.getItem('animal-totem-photos') || '{}'); const savePhotos = p => localStorage.setItem('animal-totem-photos',JSON.stringify(p));
function shell(content) { app.innerHTML = `<section class="screen">${content}</section>`; }
function home() { shell(`<div class="brand">🐾 TON TOTEM TOUT DOUX</div><h1>QUEL ANIMAL<br>ES-TU ?</h1><div class="hero-paws">🌸 🐾 🌸</div><p class="lead">Découvre l'animal qui fait battre ton cœur.</p><div class="actions"><button class="button" id="start">💗 COMMENCER</button><button class="button alt" id="gallery">📸 MA GALERIE</button></div>`); document.querySelector('#start').onclick=identity; document.querySelector('#gallery').onclick=gallery; }
function identity() { shell(`<div class="card"><div class="brand">💌 AVANT DE COMMENCER</div><h2>Comment t'appelles-tu ?</h2><p class="lead">Choisis un prénom, un nom ou ton petit pseudo.</p><label class="field">Prénom <input id="first" autocomplete="given-name" enterkeyhint="next" placeholder="Ex. Louise"></label><label class="field">Nom <input id="last" autocomplete="family-name" enterkeyhint="next" placeholder="Facultatif"></label><label class="field">Pseudo <input id="nick" enterkeyhint="done" placeholder="Ou ton pseudo préféré"></label><div class="actions"><button class="button" id="go">C'EST PARTI ! ✨</button><button class="button alt" id="back">← Retour</button></div></div>`); const first=document.querySelector('#first'), last=document.querySelector('#last'), nick=document.querySelector('#nick'); const startQuiz=()=>{const f=first.value.trim(),l=last.value.trim(),n=nick.value.trim(); state.name=n||[f,l].filter(Boolean).join(' ')||'Toi'; quiz();}; [[first,last],[last,nick],[nick,null]].forEach(([input,next])=>input.addEventListener('keydown',event=>{if(event.key!=='Enter')return; event.preventDefault(); next ? next.focus() : startQuiz();})); document.querySelector('#back').onclick=home; document.querySelector('#go').onclick=startQuiz; }
function quiz() { const q=state.question, opts=optionSets[q%optionSets.length]; shell(`<div class="progress-line"><span>QUESTION ${q+1} / ${prompts.length}</span><span>🐾</span></div><div class="progress"><i style="width:${q/prompts.length*100}%"></i></div><div class="card quiz-card"><h2 class="question">${prompts[q]}</h2><div class="answers">${opts.map((text,i)=>`<button class="answer" data-animal="${ANIMALS[i].id}">${text}</button>`).join('')}</div></div>`); document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{state.scores[b.dataset.animal]+=2; state.question++; state.question===prompts.length ? finish() : quiz();}); }
function finish(){ const ranked=[...ANIMALS].sort((a,b)=>state.scores[b.id]-state.scores[a.id]); if(state.scores[ranked[0].id]===state.scores[ranked[1].id]) bonus(ranked[0],ranked[1]); else result(ranked[0]); }
function bonus(a,b) { shell(`<div class="card"><div class="brand">💕 DERNIÈRE PETITE QUESTION</div><h2>Deux énergies te ressemblent beaucoup !</h2><p class="lead">Au choix, tu préfères suivre ton intuition ou créer une belle surprise ?</p><div class="actions"><button class="button" id="one">Suivre mon intuition ✨</button><button class="button alt" id="two">Créer une surprise 🎀</button></div></div>`); document.querySelector('#one').onclick=()=>result(a); document.querySelector('#two').onclick=()=>result(b); }
function result(animal) { state.result=animal; shell(`<div class="confetti">${['💗','🌸','✨','🐾','💖','🌷'].map((x,i)=>`<span style="left:${8+i*17}%;animation-delay:-${i*.4}s">${x}</span>`).join('')}</div><div class="card"><div class="brand">🎉 TON RÉSULTAT EST LÀ</div><p class="lead">${state.name}, tu es le</p><h2 class="result-name">${animal.name} !</h2><div class="animal">${animal.emoji}</div><p class="lead">Une personnalité <strong>${animal.description}</strong>. C'est une merveilleuse énergie à avoir près de soi !</p><div class="traits">${animal.traits.map(t=>`<span class="trait">${t}</span>`).join('')}</div><div class="actions"><button class="button" id="camera">📸 PRENDRE EN PHOTO</button><button class="button alt" id="see-gallery">📸 MA GALERIE</button><button class="button alt small" id="again">🔄 REFAIRE LE QUIZ</button></div></div>`); document.querySelector('#camera').onclick=()=>camera.click(); document.querySelector('#see-gallery').onclick=gallery; document.querySelector('#again').onclick=()=>{state={name:'',scores:Object.fromEntries(ANIMALS.map(a=>[a.id,0])),question:0,result:null};identity();}; }
camera.addEventListener('change',event=>{const file=event.target.files[0]; if(!file||!state.result)return; const reader=new FileReader(); reader.onload=()=>{const p=getPhotos(); (p[state.result.id]??=[]).push(reader.result); savePhotos(p); gallery();}; reader.readAsDataURL(file); event.target.value='';});
function gallery(){ const photos=getPhotos(), found=ANIMALS.filter(a=>photos[a.id]?.length); shell(`<div class="card"><button class="back" id="back">← Accueil</button><div class="gallery-header"><div><h2>Ma galerie 📸</h2><p class="muted">Tes souvenirs les plus précieux.</p></div><span class="counter">🐾 ${found.length} / 12</span></div>${found.length?`<div class="collection">${found.map(a=>`<button class="animal-tile" data-id="${a.id}"><span class="tile-emoji">${a.emoji}</span><span><b>${a.name}</b><small>${photos[a.id].length} photo${photos[a.id].length>1?'s':''} souvenir${photos[a.id].length>1?'s':''}</small></span></button>`).join('')}</div>`:`<p class="lead">Ta collection est encore secrète… Fais le quiz et prends une photo de ton résultat pour commencer ! 💕</p>`}</div>`); document.querySelector('#back').onclick=home; document.querySelectorAll('.animal-tile').forEach(b=>b.onclick=()=>animalGallery(ANIMALS.find(a=>a.id===b.dataset.id))); }
function animalGallery(animal){const photos=getPhotos()[animal.id]||[];shell(`<div class="card"><button class="back" id="back">← Ma galerie</button><div class="animal">${animal.emoji}</div><h2>Mes photos de ${animal.name}</h2><p class="muted">${photos.length} joli${photos.length>1?'s':''} souvenir${photos.length>1?'s':''} à garder précieusement.</p><div class="photos">${photos.map((src,i)=>`<img class="photo" src="${src}" alt="Souvenir ${i+1} - ${animal.name}">`).join('')}</div></div>`);document.querySelector('#back').onclick=gallery;}
home();
